### ISSUE TITLE
Provider org.glassfish.json.JsonProviderImpl not found

### ISSUE THREAD

**Issue by sergioasca** [joshka/junit-json-params#130]
Hi!

First of all thank you.
When I use le versión v5.9.2-r0 and run a test with an array of json, the test throw this exception:
![image](https://user-images.githubusercontent.com/94602969/226543774-7142e046-28e2-48fa-a21f-0ff896a777cf.png)
I fixed this adding this dependency:
`    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>javax.json</artifactId>
      <version>1.1.4</version>
    </dependency>`

It's really necesary?

**Comment by joshka** [comment]
It's been a while since I used maven rather than gradle. Perhaps can you provide a minimal reproducible example of the problem that you're having? My guess is that it's something to do with the scope of the dependencies in your maven file needing to be set to indicate only using the provider for tests?

Way back when this came about javax.json was the JSR 353 implementation, which I chose to avoid bringing in Jackson / Gson deps just for testing (a constraint of a project I was working on at the time). It's likely that this actually needs to be updated to use jakarta.json-api and the latest version of org.glassfish jakarta.json - which is now called parsson (see https://central.sonatype.com/search?q=jakarta.json and https://www.baeldung.com/java-json#json-p).

I'm not actively using this, so would welcome feedback from those that are.

I've put a PR at https://github.com/joshka/junit-json-params/pull/131 which would be worth checking over before I release and merge it. Could you please take a look?

**Comment by sergioasca** [comment]
Hi!
I understand that with the changes to the PR that you tell me, it should be enough to only include the dependency of the library.
If you let me know when you do the merge and the artifact is ready, I'll change the dependency and try.
Thanks

**Comment by joshka** [comment]
I'm not certain exactly how gradle dependency types map onto maven types (I'll take a look sometime in the next few days though - if you want however I'd suggest building the PR locally into your version and seeing if it fixes your issue or whether it needs to be one of the other dependency types to work.

**Comment by joshka** [comment]
I haven't really looked at this in a while. Cand you try building the PR #131 and seeing if it solves the issue. If it doesn't please provide a minimal repro in a github repo for this and I'll see what I can do.

**Comment by migueltercero** [comment]
Hi, I confirm that PR https://github.com/joshka/junit-json-params/pull/131 works with java 17 (jakarta api). You can publish new version

Regards

**Comment by joshka** [comment]
This is published now. If it is still a problem, feel free to reopen this issue.
